permalink: /:year-:month-:day/:title/

highlighter: pygments
markdown: kramdown

kramdown:
  input: GFM



paginate: 10
paginate_path: ":num"
baseurl: ""



title: "爱生活爱阿慌"
email: "xindongzhang@foxmail.com"
description: "Developer"
github_username:  "xindongzhang"
swiftype_searchId: "g_ALCBPsJ8rALyHxsMvk"
disqus_shortname: "xindongzhanggithubio"



url: "http://54dreams.com"
imgrepo: "http://54dreams.com/static/img"
#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

gems:
  - jekyll-paginate


